apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube
  labels:
    app: kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube
    
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
        - name: kube
          image: roakkennady/helloworld
          ports:
            - containerPort: 80
          imagePullPolicy: Never

---

apiVersion: v1 
kind: service
metadata:
  name: kube
  labels:
    app: kube
spec:
  ports:
  - port: 80
    tragetPort: 80
  selector:
    app: kube
  type: LoadBalancer 

    

